### ISSUE TITLE
Steep and confusing learning curve to contributing

### ISSUE THREAD

**Issue by Patater** [ARMmbed/mbed-tools#144]
### Description

It is a bit difficult to get going on this project.

Our documentation should be improved to help with this in a scalable way.

We have a DEVELOPMENT.md and another CONTRIBUTING.md. We should put all the DEVELOPMENT information into CONTRIBUTING, so that CONTRIBUTING is a self-contained guide with all the onboarding information to get going on the project.

We should show a few handy `tox` commands, too. Some of these can replace our existing documentation on how to run `pre-commit`, `black`, and `flake8` individually.
- `tox -e linting`
- `tox -e py37`
- `tox -e checknews`

We can also show how to set up `tox` on Mac and Linux, and link to Tox docs for Windows or for more information about Tox.

### Issue request type

- [X] Enhancement
- [ ] Bug

**Comment by ladislas** [comment]
I just went through the process today with macOS Big Sur, so my $0.02 :)

- brew installs python@3.9 now, there are now mentions of python 3.9 in the documentation so that can be a little confusing (I don't have a python background so it might be obvious for you guys)
- the documentation for pre-commit says it will run pytest but it's not the case. it took me some time to figure out that I just need to run `pytest` -- I had found a workaround with `tox -e py39` but it messed everything up.
- i was not able to install everything with `tox -e dev` -- jellyfish in particular was failing. I has to install the requirements system wide to make it work
- the news file error message is cryptic if you don't know what it is, maybe pre-commit could create the file

I'm a big fan of Makefiles for pretty much everything that needs to call a script. `make install_deps`, `make install_tox`, `make setup_env`, `make test`, etc. could be easier as users won't have to know or remember the specific commands. It's also easier to open the Makefile and see what you can do with it than getting lost in documentation.
